### ISSUE TITLE
Fatal Error: missing jpeglib.h

### ISSUE THREAD

**Issue by GabrielRRussell** [xerpi/sfillib#5]
sfillib won't compile at all, when using 

> make install

I tried it in a root terminal too, still won't work.

The error seems to come from a missing header file: jpeglib.h, and I don't see it present in any directory for this repository. Was it removed in a random commit? I can't find it anywhere. 

I'm using this primarily for Spritetools, but considering spritetools literally just downloads the files and then compiles them, I just downloaded this and tried compiling it. Both the spritetools and fresh download fail compilation.

>  /home/pi/Downloads/SpriteTools-2.2/dependencies/libsfil/libsfil/source/sfil_jpeg.c:5:21: fatal error: jpeglib.h: No such file or directory
 #include <jpeglib.h>
                     ^
compilation terminated.
/opt/devkitpro/devkitARM/base_rules:84: recipe for target 'sfil_jpeg.o' failed
make[2]: *** [sfil_jpeg.o] Error 1
Makefile:95: recipe for target 'build' failed
make[1]: *** [build] Error 2
Makefile:169: recipe for target '/opt/devkitpro/libctru/lib/libsfil.a' failed
make: *** [/opt/devkitpro/libctru/lib/libsfil.a] Error 2

**Comment by xerpi** [comment]
You have to install libjpeg: https://github.com/devkitPro/3ds_portlibs
Also keep in mind that sf2d is deprecated.

**Comment by GabrielRRussell** [comment]
EDIT: Solved!

I unzipped the 3DS Portable Libs. From there I CD'd to it, and did 

> make install libjpeg

And then installed sfillib. It works!
